name: Build & Deploy Code

on: [push,pull_request]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v4
      - name: print something on console
        run:  echo "Hello linux 2nd timeasdasdasd"
#  push:
#    branches:
#      - "dev"
#  pull_request:
#    branches:
#      - "test_branch"asasdadadasd