name: Build & Deploy Code

on: [push,pull_request]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v4
      - name: print something on console
        run:  echo "Hello linux 2nd"
      - name: install python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: print working directory
        run: pwd
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install dependencies
        run: pip install -r requirements.txt

#  push:
#    branches:
#      - "dev"
#  pull_request:
#    branches:
#      - "test_branch"asasdadadasd