name: Build & Deploy Code

on: [push,pull_request]

jobs:
  job1:

    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v4
      - name: print something on console
        run:  echo "Hello linux 3rd"
      - name: install python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: update pip
        run: python -m pip install --upgrade pip

      - name: install dependencies
        run: pip install -r requirements.txt

      - name: Run the app
        run: | 
            pip install uvicorn
            uvicorn app2.main:app
          

      - name: Capture response
        id: app_get_response
        run: response=$(curl -s http://127.0.0.1:8000/) 
          echo "::set-output name=response::$response"

      - name: Print GET response
        run: echo "Response from Get request:${{steps.app_get_response.outputs.response}}"
#  push:
#    branches:
#      - "dev"
#  pull_request:
#    branches:
#      - "test_branch"asasdadadasd